package io.irontest;

/**
 * Created by Zheng on 1/05/2016.
 */
public interface IronTestConstants {
    String DB_UNIQUE_NAME_CONSTRAINT_NAME_SUFFIX = "UNIQUE_NAME_CONSTRAINT";
    String DB_PROPERTY_NAME_CONSTRAINT_NAME_SUFFIX = "PROPERTY_NAME_CONSTRAINT";
    String DB_USERNAME_CONSTRAINT_NAME_SUFFIX = "USERNAME_CONSTRAINT";

    String ENDPOINT_PASSWORD_ENCRYPTION_KEY = "8888";
    String IMPLICIT_PROPERTY_NAME_TEST_CASE_START_TIME = "Test_Case_Start_Time";
    String IMPLICIT_PROPERTY_NAME_TEST_STEP_START_TIME = "Test_Step_Start_Time";
    String IMPLICIT_PROPERTY_DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss.SSS";
}
